"""push_briefing.py - 北京时间8点运行，读取已生成的简报JSON推送到微信
不调用任何AI接口，纯读取+推送，秒级完成。
"""
import requests, json, os
from datetime import datetime, timedelta, timezone

PUSHPLUS_TOKEN = os.environ.get("PUSHPLUS_TOKEN", "")

def push_to_wechat(title, content):
    if not PUSHPLUS_TOKEN:
        print("  [PushPlus] 未配置token，跳过")
        return False
    try:
        payload = {"token": PUSHPLUS_TOKEN, "title": title, "content": content, "template": "html"}
        resp = requests.post("http://www.pushplus.plus/send", json=payload, timeout=15)
        result = resp.json()
        if result.get("code") == 200:
            print(f"  [PushPlus] 推送成功")
            return True
        else:
            print(f"  [PushPlus] 失败: {result.get('msg', 'unknown')}")
            return False
    except Exception as e:
        print(f"  [PushPlus] error: {e}")
        return False

def main():
    base_dir = "."
    now = datetime.now(timezone.utc)
    bj_time = now.astimezone(timezone(timedelta(hours=8))).strftime("%Y-%m-%d %H:%M")
    # 推送今天的简报（当天北京时间8点，对应今天的日期）
    # 凌晨生成的简报用的是北京日期，这里也用北京日期
    date_str = now.astimezone(timezone(timedelta(hours=8))).strftime("%Y-%m-%d")
    print(f"=== 推送简报 {bj_time} ===")

    # 读取简报JSON
    briefing_path = os.path.join(base_dir, "articles/daily", f"{date_str}_briefing.json")
    if not os.path.exists(briefing_path):
        print(f"  未找到简报文件: {briefing_path}")
        # 尝试昨天的（防止凌晨生成失败或时区边界问题）
        yesterday = (now - timedelta(days=1)).astimezone(timezone(timedelta(hours=8))).strftime("%Y-%m-%d")
        briefing_path = os.path.join(base_dir, "articles/daily", f"{yesterday}_briefing.json")
        if not os.path.exists(briefing_path):
            print(f"  也未找到昨天简报: {briefing_path}")
            return
        date_str = yesterday
        print(f"  回退使用昨天简报: {date_str}")

    with open(briefing_path, "r", encoding="utf-8") as f:
        briefing_data = json.load(f)

    articles = briefing_data.get("articles", [])
    commentary = briefing_data.get("commentary", "")
    commentary_title = briefing_data.get("commentary_title", "")

    if not articles:
        print("  简报中无文章，跳过推送")
        return

    # 组装HTML
    html_parts = [f'<h2>Daily Briefing | {date_str}</h2>']
    html_parts.append(f'<p><b>Total: {len(articles)} in-depth articles</b></p>')
    html_parts.append('<hr>')

    for a in articles:
        source_tag = "SCMP" if a.get("source") == "scmp" else "Caixin Global"
        html_parts.append(f'<h3>[{source_tag}] {a["title"]}</h3>')
        html_parts.append(f'<p>Words: {a.get("word_count", "N/A")} | <a href="{a.get("url", "")}">Original</a></p>')
        if a.get("summary"):
            html_parts.append(f'<p><b>Summary:</b></p>')
            html_parts.append(f'<blockquote>{a["summary"]}</blockquote>')
        html_parts.append('<hr>')

    if commentary:
        html_parts.append('<h2>Political Economy Analysis</h2>')
        if commentary_title:
            html_parts.append(f'<p><i>Analyzing: {commentary_title}</i></p>')
        html_parts.append(f'<div style="font-family:sans-serif;line-height:1.8">{commentary.replace(chr(10), "<br>")}</div>')
        html_parts.append('<hr>')

    html_parts.append(f'<p style="color:#999;font-size:10pt">Generated by caixin-monitor | <a href="https://github.com/1151785600-hue/caixin">GitHub</a></p>')
    full_html = "\n".join(html_parts)

    # 同时保存HTML版本
    html_path = os.path.join(base_dir, "articles/daily", f"{date_str}_briefing.html")
    with open(html_path, "w", encoding="utf-8") as f:
        f.write(full_html)

    # 推送
    push_title = f"Daily Briefing | {date_str} | {len(articles)} articles"
    push_to_wechat(push_title, full_html)
    print(f"\n=== 推送完成 ===")

if __name__ == "__main__":
    main()
